### ISSUE TITLE
Tests for add_max_mesh_objective

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#29]
The tests for `add_max_mesh_objective()` are incomplete. Here's some ideas:
1. Verify that solving a toy problem with this objective yields a "correct" solution.

**Comment by dimitri-justeau** [comment]
I was wondering if it would not be better to rename objective functions to `set_xxx_objective()` (e.g. `set_max_mesh_objective()` ? The reason is that there is only one objective attached to a problem, so we do not really add it, instead of constraints that can be multiple in one problem. Would it be ok for you @jeffreyhanson ?

**Comment by jeffreyhanson** [comment]
Ooh - interesting point! 

Yeah, I agree it could be confusing to have `add_*` for both objectives and other stuff given different behaviors. In prioritizr, we throw a warning when the users tries to define an objective twice for a problem (to let them know that the previous objective is being overwritten) - but that might not be ideal. I guess the downside with this approach would be that users need to remember to use `set_*` for objectives and `add_*` for everything else - and that might be a bit confusing. Are there other instances where using `set_*` makes more sense too? E.g., what about parameters? If you think having both `add_*` and `set_*` could be confusing, we could just drop those prefixes and have (for example) `max_mesh_objective()*` ? 

Personally, I think there pro's and con's with any of these approaches, so I'm happy with what ever approach you think is best?

**Comment by dimitri-justeau** [comment]
I think it is nice to throw a warning when the objective (or an already defined constraint) is overwritten. Maybe `set_settings` would make sense also. I am not really in favour of abandoning prefixes, as they are informative about the object model and the relations between the package components. Also, I do not think that it will be confusing to have `add_*` and `set_*` prefixes if the package is well documented. In most libraries and programming languages it is very common to have several prefixes that are informative about the relations between objects, for instance adding, removing, or getting an element to/from a list, which indicates a one-to-many relationship between the list and its elements. Or for instance, if we have a map, we set a coordinate reference system, because there is a one-to-one relationship between the map and its coordinate reference system.

This is why I prefer using `set_x` for objective, as one problem is associated with one objective. Am I convincing? 😇

**Comment by jeffreyhanson** [comment]
I see, thanks for explaining all that! Yeah - that's very good point that it's common for programming libraries to use multiple verbs - let's go with having `add_*` and `set_*`.

**Comment by dimitri-justeau** [comment]
Ok I modified it with https://github.com/dimitri-justeau/restoptr/commit/696b32c2e1023af2d9e8855cbf30d2aec5589263

Also, the tests for max MESH and max IIC where, to my opinion, already sufficient. Please feel free to reopen if you disagree !
