### ISSUE TITLE
package vignette

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#36]
The package vignette is incomplete. It would be great to have the package vignette ready before initial release.

**Comment by jeffreyhanson** [comment]
@dimitri-justeau, I've drafted most of the text and code for the vignette (see vign2 branch). I'm having trouble generating multiple solutions and keep getting this error message:

```
Error in solve.RestoptProblem(.) : failed to complete optimization
         Error in rJava::.jcall(jproblem, "Ljava/util/List;", "maximizeMESH", nb_solutions,  : 
  java.lang.NullPointerException
```

Do you have any idea what I'm doing wrong? For reference, here's a reprex:

```
# load package
library(devtools)
load_all()

# load data
habitat_data <- rast(system.file(
  "extdata", "habitat_hi_res.tif", package = "restoptr"
))
locked_out_data <- rast(system.file(
  "extdata", "locked_out.tif", package = "restoptr"
))

rp <-
  restopt_problem(
    existing_habitat = habitat_data,
    aggregation_factor = 16,
    habitat_threshold = 0.7
  ) %>%
  set_max_mesh_objective() %>%
  add_restorable_constraint(
    min_restore = 1, max_restore = 2000, unit = "ha"
  ) %>%
  add_compactness_constraint(5, unit = "km") %>%
  add_locked_out_constraint(data = locked_out_data) %>%
  add_settings(nb = 1000)

# generate solutions
solve(rp)
```

**Comment by dimitri-justeau** [comment]
There was a bug in the Java code, which happened when more than 1 solution is requested and the time limit is 0. I fixed this bug in https://github.com/dimitri-justeau/restopt/commit/448b735b942de06b306739e3a0d393e6c47826c5

The jar file in restoptr is also fixed :-)

**Comment by dimitri-justeau** [comment]
Sorry I closed this issue while I should not have. I had a look at the vign2 branch, the getting started vignette looks awesome ! I see that you propose a portfolio approach, which makes me think of a new feature that we could implement in `restoptr`: getting something like 1000 optimal solutions while maximizing MESH or IIC is likely to return less than 1000 solutions, because there are probably few optimal solutions. But what we could do is (i) find the optimal value and (ii) rerun a restopt problem where we constrain the optimization objective to be within 5% (or another value which can be chosen) of the optimal value. I think that we can implement this process exclusively in R. What do you think of this?

**Comment by jeffreyhanson** [comment]
Thanks! Yeah, how hard would it be to add the functionality to specify a gap? I think it could be extremely useful, but I understand if it would be too tricky to implement? Since we're getting rid of the `set_settings()` function, should this gap parameter be in the `solve()` function?
