### ISSUE TITLE
package NOTE

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#53]
I noticed that the package checks in the GitHub Actions throw this NOTE:

> checking R code for possible problems ... [17s/17s] NOTE
>  File ‘restoptr/R/zzz.R’:
>    .onLoad calls:
>      packageStartupMessage("Downloading Java software to generate prioritizations...")

I was wondering if you had any ideas for addressing this? Ideally, we want to remove all NOTES to avoid issues with the CRAN submission.

**Comment by dimitri-justeau** [comment]
Hi Jeff,

From what I've read here: https://r-pkgs.org/r-cmd-check.html , the NOTE appears because `packageStartupMessage` is called from `.onLoad()`. Apparently, it should be called from `.onAttach()` :

> Put [library.dynam()](https://rdrr.io/r/base/library.dynam.html) in [.onLoad()](https://rdrr.io/r/base/ns-hooks.html), not [.onAttach()](https://rdrr.io/r/base/ns-hooks.html); put [packageStartupMessage()](https://rdrr.io/r/base/message.html) in [.onAttach()](https://rdrr.io/r/base/ns-hooks.html), not [.onLoad()](https://rdrr.io/r/base/ns-hooks.html). Put [library.dynam.unload()](https://rdrr.io/r/base/library.dynam.html) in [.onUnload()](https://rdrr.io/r/base/ns-hooks.html). If you use any of these functions, make sure they’re in the right place.

Finally, as we will be able to include the jar in the package archive, downloading it might not be necessary. So we have two options:

1. Remove the `packageStartupMessage` call. Indeed, we cannot move the download procedure to `.onAttach()`, because `rJava` needs the Jar to be loaded in `.onLoad()`.

2. Remove the download procedure, as it is probably now useless.

I will try to implement the second option, and see if our tar.gz archive is effectively less than 5mb in total.

**Comment by dimitri-justeau** [comment]
Okay, so I implemented the second option, the package archive is 3.8mb so we shouldn't have any problem with CRAN submission with the Jar included in the archive. The only note that remains is related to the DOI of the JAE paper (the DOI is correct, it is just the way that CRAN uses to check DOIs and URL which is bugged). I think that this note shouldn't be a problem for submission. There is also an invalid URL note about the resptotr website URL, which is normal since it is not yet online :-)

**Comment by jeffreyhanson** [comment]
That's brilliant - thank you!
